version: '3'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    restart: always
    environment:
      CLICKHOUSE_DB: data4trend
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: 123456
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./scripts/clickhouse-init.sql:/docker-entrypoint-initdb.d/init.sql
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      clickhouse:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_HTTP_PORT=8123
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=123456
      - CLICKHOUSE_DATABASE=data4trend
      - BINANCE_API_KEY=
      - BINANCE_SECRET_KEY=
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs

volumes:
  clickhouse_data:
