binance:
  api_key: ""  # 不需要API密钥就可以获取公共K线数据
  secret_key: ""

mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "123456"
  database: "data4trend"

server:
  port: 8080
  env: development

http:
  timeout: 30
  proxy: "http://127.0.0.1:7890"  # 如果需要代理，请设置，否则留空
  
# 币种配置文件路径
symbols_config_path: "config/symbols.yaml"

log:
  level: "debug"
  json_format: false
  output_path: "logs/dataFeeder.log"
