# 币种配置
groups:
  # 空组，不再使用主交易对组
  
# 全局设置
settings:
  max_symbols_per_batch: 30  # 每批处理的币种数，增加到30个
  discovery_enabled: true # 启用自动发现新币种
  discovery_interval: 6h # 缩短自动发现新币种的间隔
  excluded_symbols: # 排除的币种
    - USDCUSDT
    - BUSDUSDT
    - TUSDUSDT
