# 币种配置
groups:
  # 主交易对组，用于自动发现的币种
  main:
    symbols: []  # 将由程序自动填充市值排名前200的币种
    intervals: ["15m", "1h", "1d"]  # 支持的时间周期
    start_times:
      minute: "2025-01-01T00:00:00Z"  # 分钟级数据开始时间
      hour: "2025-01-01T00:00:00Z"    # 小时级数据开始时间
      day: "2023-01-01T00:00:00Z"     # 日级数据开始时间
    enabled: true
    poll_intervals:
      "15m": "15m"
      "1h": "1h" 
      "1d": "24h"
  
# 全局设置
settings:
  max_symbols_per_batch: 30  # 每批处理的币种数，增加到30个
  discovery_enabled: true # 启用自动发现新币种
  discovery_interval: 6h # 缩短自动发现新币种的间隔
  excluded_symbols: # 排除的币种
    - USDCUSDT
    - BUSDUSDT
    - TUSDUSDT
  # 全局开始时间配置，适用于所有新发现的币种
  global_start_time: "2025-01-01T00:00:00Z"  # 币种数据收集的全局开始时间
