# 币种配置
groups:
  # 主交易对组
  main:
    symbols: []  # 将由程序自动获取前200个市值最大的币种
    intervals: ["15m", "4h", "1d"]  # 仅支持这三个时间周期
    start_times:
      minute: "2023-01-01T00:00:00Z"
      hour: "2023-01-01T00:00:00Z"
      day: "2023-01-01T00:00:00Z"
    enabled: true
    poll_intervals:
      "15m": 15m
      "4h": 4h
      "1d": 24h

# 全局设置
settings:
  max_symbols_per_batch: 20 # 每批处理的最大币种数
  discovery_enabled: false # 是否启用自动发现新币种
  discovery_interval: 24h # 自动发现新币种的间隔
  excluded_symbols: # 排除的币种
    - USDCUSDT
    - BUSDUSDT
    - TUSDUSDT
